name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/coverage.svg"
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.1
    - name: Run tests
      run: deno test --coverage=cov_profile
    - name: Generate lcov report
      run: deno coverage ./cov_profile --lcov --output=cov_profile/cov.lcov
    - name: Send coverage to Code Climate
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: 8d3f4248acef2f4ba4b7b406233206968ec732c22e0d51477b77da0071bdbfda
      with:
        coverageLocations: |
          ${{github.workspace}}/cov_profile/cov.lcov:lcov
