name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/coverage.svg"
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.1
    - name: Run tests
      run: deno test --coverage=cov_profile
    - name: Generate lcov report
      run: deno coverage ./cov_profile --lcov --output=cov_profile/cov.lcov
    - uses: ImBIOS/lcov-coverage-badge@v1
      with:
        file: ./cov_profile/cov.lcov
